[package]
name = "hdr_histogram"
version = "0.0.1"
authors = [ "Octavian Geagla <ogeagla@gmail.com>", "Marshall Pierce <marshall@mpierce.org>" ]

[dependencies]
num = "0.1"
byteorder = "0.5.1"
rand = "0.3"
